version: "3.9"

services:
  backend:
    build: ./backend
    container_name: employee-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app  # optional for hot reload

  frontend:
    build: ./frontend
    container_name: employee-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    depends_on:
      - backend
